### ISSUE TITLE
Problem faced in starting application

### ISSUE THREAD

**Issue by waqas491** [named-data/ChronoChat#3]
Respected Sir,
My name is Waqas Awan. I am currently working with my master thesis and I have problem with the starting of ChronoChat application. I build chronochat on GTS Testbed and when I want to start the application (chronochat) after build, the demo icon is not display on the top of the window. I clicked many time but its not showing any icon in order to start application. Please help me in this problem. I shall be very thankful to you.

**Comment by Pesa** [comment]
Closing old/stale issue.
